rnn_cnn:
  epoch: 200
  dropout: 0.05 
  conv: 
    n_kernels: 
      - [16, 32, 64]
      - [16, 32, 64]
      - [16, 32, 64]
      - [16, 32, 64]
    kernel_s: 
      - [7, 5, 3]
      - [7, 5, 3]
      - [7, 5, 3]
      - [7, 5, 3]
  lstm: 
    bi_unit: [64,64,64,64]
    si_unit: [128,128,128,128]
  optimizer: 'adam'
  loss: 'mse'
  lr: [0.0001, 0.0001, 0.0001, 0.0001]